/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Defines the server account schema.
 */
export interface AccountSchema {
  uuid: string;
  bank_name: string;
  account_name: string;
  currency: string;
  created_at: string;
}
