/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Represents an Account.
 */
export interface Account {
  token: string;
  uuid: string;
  type: string;
  default_category: string;
  currency: string;
  created: string;
  name: string;
}
