/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Defines the server account balance schema.
 */
export interface AccountBalanceSchema {
  uuid: string;
  cleared_balance: number;
  pending_transactions: number;
  effective_balance: number;
}
