/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetTransactionsForAccountIdBetweenParams = {
  start_date?: string;
  end_date?: string;
};
