/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StarlingAccounts } from "./starlingAccounts";

/**
 * Models the Starling account for the given access token.
 */
export interface MainAccount {
  type_name: string;
  token?: string;
  accounts: StarlingAccounts;
}
