/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey,
} from "react-query";
import type { AccountBalance } from "./models";
import { useAxios } from "../useAxios";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

/**
 * @summary Get Balances
 */
export const useGetBalancesHook = () => {
  const getBalances = useAxios<AccountBalance[]>();

  return () => {
    return getBalances({ url: `/balances`, method: "get" });
  };
};

export const getGetBalancesQueryKey = () => [`/balances`];

export const useGetBalances = <
  TData = AsyncReturnType<ReturnType<typeof useGetBalancesHook>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    AsyncReturnType<ReturnType<typeof useGetBalancesHook>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options || {};

  const queryKey = queryOptions?.queryKey ?? getGetBalancesQueryKey();

  const getBalances = useGetBalancesHook();

  const queryFn: QueryFunction<
    AsyncReturnType<ReturnType<typeof useGetBalancesHook>>
  > = () => getBalances();

  const query = useQuery<
    AsyncReturnType<ReturnType<typeof useGetBalancesHook>>,
    TError,
    TData
  >(queryKey, queryFn, queryOptions);

  return {
    queryKey,
    ...query,
  };
};
